/**
 * The category bank.
 *
 * Every level is four of these, four words from each. Nothing else in the game
 * knows what a word means, so **this file is the whole of what the solver can
 * see** — a word that plainly belongs to a category but is missing from its
 * list is invisible to the uniqueness check, and that is the one way a board
 * can ship with two answers. Lists are therefore written to be complete for the
 * short, common words, which are the ones that turn up in other lists.
 *
 * Overlaps are the point, not an accident. `BASS` is a fish and an instrument,
 * `EAGLE` is a bird, a golf score and a yoga pose, `PYTHON` is a snake and a
 * programming language. The generator leans on exactly these to plant red
 * herrings, and the solver is what keeps them fair: a board ships only if the
 * sixteen words split into four groups one way and one way only, across every
 * category here, not just the four that were chosen.
 *
 * Tiers run 1 (plain membership: Fish) to 4 (wordplay: FIRE ___). They decide
 * the colour of a solved group — yellow, green, blue, purple, easiest first —
 * and weight how readily the naive player in `solve.ts` spots a group.
 *
 * Format: `tier|Name|WORD WORD WORD`, and an optional fourth field naming a
 * family. Two categories in one family never share a board, for pairs that are
 * the same idea twice (Shakespeare's plays and his characters) where splitting
 * them would be a coin toss rather than a deduction.
 */

export interface Category {
  id: number;
  name: string;
  tier: 1 | 2 | 3 | 4;
  words: readonly string[];
  family: string | null;
}

/**
 * Categories whose membership is a spelling rule rather than a list.
 *
 * A list cannot be complete for "contains a hidden number" — `MONEY`, `KITTEN`
 * and `STONE` all qualify and they come from three unrelated lists — so these
 * are tested against every word in the bank instead, and `seed` only supplies
 * members that no other category happens to contain.
 */
interface RuleCategory {
  tier: 4;
  name: string;
  test: (word: string) => boolean;
  seed: string;
}

const LISTS = `
1|Fish|BASS PIKE CARP COD TROUT SALMON PERCH TUNA HALIBUT SOLE HADDOCK MACKEREL SARDINE SNAPPER MINNOW FLOUNDER HERRING ANCHOVY RAY EEL PLAICE
1|Birds|ROBIN CROW SWALLOW FINCH EAGLE HAWK OWL PARROT PIGEON SPARROW WREN CRANE HERON RAVEN STORK DOVE LARK JAY SWIFT KITE CONDOR ALBATROSS PENGUIN OSTRICH TURKEY DUCK GOOSE SWAN MAGPIE PELICAN FALCON CARDINAL TERN GULL
1|Trees|OAK ELM ASH PINE MAPLE BIRCH CEDAR WILLOW SPRUCE FIR BEECH POPLAR REDWOOD CYPRESS HICKORY ALDER HOLLY YEW PALM LARCH SYCAMORE
1|Planets|MERCURY VENUS EARTH MARS JUPITER SATURN URANUS NEPTUNE
1|Fruits|APPLE BANANA CHERRY GRAPE LEMON LIME MANGO ORANGE PEACH PEAR PLUM KIWI DATE FIG MELON PAPAYA APRICOT GUAVA OLIVE
1|Vegetables|CARROT CELERY LETTUCE ONION POTATO SPINACH CABBAGE PEPPER RADISH TURNIP SQUASH LEEK KALE BEET PEA CORN ASPARAGUS BROCCOLI PARSNIP
1|Colors of the rainbow|RED ORANGE YELLOW GREEN BLUE INDIGO VIOLET
1|Shades of blue|NAVY TEAL COBALT AZURE SAPPHIRE INDIGO CYAN ROYAL SKY BABY CERULEAN
1|Shades of red|CRIMSON SCARLET RUBY MAROON CHERRY BRICK CARDINAL BURGUNDY ROSE WINE
1|Shades of green|LIME OLIVE EMERALD JADE MINT SAGE FOREST KELLY HUNTER PISTACHIO
1|Dog breeds|BEAGLE BOXER POODLE PUG HUSKY COLLIE CORGI BULLDOG DALMATIAN TERRIER POINTER SETTER RETRIEVER GREYHOUND CHIHUAHUA SPANIEL DACHSHUND MASTIFF WHIPPET
1|Musical instruments|PIANO GUITAR VIOLIN DRUM FLUTE TRUMPET CELLO HARP BASS TUBA OBOE CLARINET BANJO ORGAN SAXOPHONE TROMBONE UKULELE HORN VIOLA BUGLE
1|Sports|TENNIS GOLF SOCCER HOCKEY RUGBY CRICKET BASEBALL BOXING POLO SQUASH BADMINTON LACROSSE VOLLEYBALL FOOTBALL BASKETBALL
1|Card games|POKER BRIDGE RUMMY HEARTS SNAP SPADES CANASTA EUCHRE CRIBBAGE SOLITAIRE BLACKJACK WAR SPOONS
1|Board games|CHESS CHECKERS MONOPOLY SCRABBLE CLUE RISK SORRY TROUBLE BATTLESHIP OTHELLO GO BACKGAMMON
1|Weather|RAIN SNOW HAIL SLEET FOG WIND THUNDER LIGHTNING DRIZZLE MIST FROST
1|Kitchen utensils|WHISK LADLE SPATULA TONGS PEELER GRATER COLANDER SIEVE MASHER CORKSCREW SPOON FORK KNIFE
1|Furniture|CHAIR TABLE SOFA DESK BED DRESSER STOOL BENCH COUCH OTTOMAN CABINET WARDROBE BOOKCASE
1|Tools|HAMMER WRENCH DRILL SAW PLIERS CHISEL SCREWDRIVER LEVEL CLAMP FILE RASP MALLET
1|Clothing|SHIRT PANTS JACKET SWEATER SKIRT DRESS SOCKS COAT SCARF BLOUSE VEST JEANS SHORTS
1|Footwear|BOOT SANDAL SNEAKER LOAFER SLIPPER CLOG PUMP MULE STILETTO WEDGE OXFORD MOCCASIN
1|Hats|CAP BERET FEDORA BOWLER BEANIE STETSON SOMBRERO TURBAN BONNET HELMET TRILBY PANAMA DERBY
1|Boats|CANOE KAYAK YACHT FERRY RAFT DINGHY BARGE SLOOP GONDOLA SCHOONER TUG SUB LINER JUNK
1|Farm animals|COW PIG SHEEP GOAT HORSE CHICKEN DUCK GOOSE DONKEY TURKEY LLAMA
1|Insects|ANT BEE WASP FLY MOTH BEETLE CRICKET GNAT FLEA LOUSE TERMITE CICADA HORNET MANTIS
1|Reptiles|SNAKE LIZARD TURTLE TORTOISE GECKO IGUANA CROCODILE ALLIGATOR COBRA PYTHON CHAMELEON
1|Big cats|LION TIGER LEOPARD JAGUAR CHEETAH PUMA COUGAR LYNX PANTHER OCELOT
1|Gemstones|DIAMOND RUBY EMERALD SAPPHIRE OPAL PEARL TOPAZ JADE AMETHYST GARNET ONYX AMBER JET
1|Metals|IRON COPPER GOLD SILVER TIN LEAD ZINC NICKEL STEEL BRASS BRONZE PLATINUM CHROME ALUMINUM TITANIUM
1|Herbs|BASIL THYME SAGE MINT PARSLEY ROSEMARY OREGANO DILL CHIVE CORIANDER TARRAGON
1|Spices|CUMIN PAPRIKA NUTMEG CINNAMON CLOVE GINGER TURMERIC SAFFRON PEPPER ANISE CARDAMOM MACE
1|Pasta|PENNE FUSILLI LINGUINE RAVIOLI LASAGNA MACARONI SPAGHETTI RIGATONI ORZO TORTELLINI FARFALLE GNOCCHI ZITI
1|Cheeses|CHEDDAR BRIE GOUDA FETA SWISS COLBY EDAM STILTON PARMESAN MOZZARELLA RICOTTA CAMEMBERT JACK
1|Breads|BAGEL BAGUETTE BRIOCHE CIABATTA PITA RYE SOURDOUGH NAAN ROLL BUN CROISSANT MUFFIN SCONE TORTILLA
1|Desserts|CAKE PIE TART PUDDING MOUSSE SUNDAE BROWNIE COOKIE FUDGE TRIFLE SORBET CUSTARD
1|Nuts|ALMOND CASHEW PECAN WALNUT PEANUT HAZELNUT PISTACHIO MACADAMIA CHESTNUT ACORN
1|Months|JANUARY FEBRUARY MARCH APRIL MAY JUNE JULY AUGUST SEPTEMBER OCTOBER NOVEMBER DECEMBER
1|Countries|FRANCE SPAIN ITALY GERMANY CHINA JAPAN INDIA BRAZIL CANADA MEXICO EGYPT PERU CHILE CUBA CHAD JORDAN TURKEY GREECE KENYA NEPAL OMAN MALI IRAN IRAQ GEORGIA
1|US states|TEXAS OHIO UTAH IOWA MAINE IDAHO ALASKA NEVADA OREGON GEORGIA INDIANA KANSAS MONTANA VERMONT FLORIDA
1|Capital cities|PARIS ROME LONDON MADRID BERLIN TOKYO CAIRO LIMA OSLO DUBLIN VIENNA ATHENS MOSCOW OTTAWA
1|Chess pieces|KING QUEEN ROOK BISHOP KNIGHT PAWN
1|Shapes|CIRCLE SQUARE TRIANGLE OVAL DIAMOND HEART STAR CROSS HEXAGON CUBE SPHERE CONE CYLINDER PYRAMID PRISM RECTANGLE
1|Card suits|HEARTS DIAMONDS CLUBS SPADES
1|Units of length|INCH FOOT YARD MILE METER FATHOM FURLONG LEAGUE CUBIT
1|Units of time|SECOND MINUTE HOUR DAY WEEK MONTH YEAR DECADE CENTURY
1|Currencies|DOLLAR EURO POUND YEN PESO RUPEE FRANC RAND LIRA KRONA WON REAL YUAN DINAR MARK
1|Zodiac signs|ARIES TAURUS GEMINI CANCER LEO VIRGO LIBRA SCORPIO SAGITTARIUS CAPRICORN AQUARIUS PISCES
1|Greek letters|ALPHA BETA GAMMA DELTA EPSILON THETA IOTA KAPPA LAMBDA SIGMA OMEGA PI RHO TAU PHI CHI PSI MU NU XI ETA ZETA
1|Dances|TANGO WALTZ SALSA RUMBA FOXTROT SAMBA POLKA JIVE CHARLESTON TWIST MAMBO BALLET DISCO
1|Music genres|JAZZ BLUES ROCK PUNK FOLK SOUL FUNK DISCO REGGAE COUNTRY METAL POP RAP GOSPEL
1|Rooms|KITCHEN BEDROOM BATHROOM ATTIC CELLAR PANTRY LOUNGE STUDY DEN HALL LIBRARY GARAGE OFFICE NURSERY PARLOR
1|Flowers|ROSE TULIP DAISY LILY IRIS ORCHID POPPY VIOLET PANSY DAHLIA LILAC PEONY MARIGOLD SUNFLOWER DAFFODIL
1|Sea mammals|WHALE DOLPHIN SEAL WALRUS OTTER MANATEE PORPOISE ORCA
1|Shellfish|CRAB LOBSTER SHRIMP OYSTER CLAM MUSSEL SCALLOP PRAWN COCKLE WHELK CRAYFISH
1|Rodents|MOUSE RAT HAMSTER GERBIL SQUIRREL BEAVER CHIPMUNK PORCUPINE MARMOT VOLE CAPYBARA
1|Candy|TOFFEE FUDGE LOLLIPOP GUMDROP LICORICE CARAMEL NOUGAT TRUFFLE MARSHMALLOW JELLYBEAN
1|Punctuation|COMMA PERIOD COLON HYPHEN DASH APOSTROPHE BRACKET SLASH ASTERISK
1|Office supplies|STAPLER PEN PENCIL ERASER RULER TAPE CLIP BINDER MARKER FOLDER SCISSORS
1|Baby animals|CUB KID CALF FOAL LAMB PUP KIT JOEY CHICK PIGLET FAWN KITTEN DUCKLING TADPOLE
1|Fantasy creatures|DRAGON UNICORN GRIFFIN PHOENIX TROLL GOBLIN ELF DWARF FAIRY OGRE CENTAUR MERMAID GNOME
1|Kitchen appliances|OVEN STOVE TOASTER BLENDER KETTLE FRIDGE FREEZER MICROWAVE DISHWASHER MIXER
1|Garden tools|RAKE HOE SPADE SHOVEL TROWEL SHEARS PRUNER MOWER TRIMMER
1|Storms|HURRICANE TORNADO CYCLONE TYPHOON BLIZZARD MONSOON SQUALL GALE TEMPEST
1|Jewelry|RING NECKLACE BRACELET ANKLET BROOCH EARRING PENDANT TIARA LOCKET CHOKER BANGLE CUFFLINK
1|Bedding|SHEET BLANKET PILLOW DUVET QUILT COMFORTER THROW
1|Coffee drinks|LATTE MOCHA ESPRESSO CAPPUCCINO AMERICANO MACCHIATO CORTADO RISTRETTO AFFOGATO
1|Spirits|GIN RUM VODKA WHISKEY BRANDY TEQUILA SCOTCH BOURBON COGNAC MEZCAL SAKE
1|Breakfast foods|PANCAKE WAFFLE BACON EGGS TOAST CEREAL OATMEAL BAGEL MUFFIN SAUSAGE HASH GRITS OMELET CREPE
1|Citrus fruits|LEMON LIME ORANGE GRAPEFRUIT TANGERINE CLEMENTINE KUMQUAT SATSUMA POMELO MANDARIN YUZU
1|Grains|WHEAT RICE OATS BARLEY RYE CORN MILLET QUINOA SPELT SORGHUM BUCKWHEAT
1|Snakes|COBRA PYTHON VIPER ADDER MAMBA BOA ASP RATTLER ANACONDA KRAIT COPPERHEAD
1|Primates|APE CHIMP GORILLA LEMUR BABOON ORANGUTAN MACAQUE GIBBON MONKEY
1|Fabrics|SILK COTTON WOOL LINEN DENIM VELVET SATIN TWEED LACE CORDUROY FLEECE NYLON SUEDE CASHMERE CHIFFON
1|Vehicles|CAR BUS TRUCK VAN TRAIN TAXI TRAM BIKE SCOOTER TRACTOR

2|Steal|ROB NICK PINCH LIFT SWIPE POACH PILFER NAB SNATCH LOOT
2|Nonsense|BUNK BALONEY DRIVEL HOGWASH TRIPE RUBBISH GARBAGE TOSH HOOEY BOSH POPPYCOCK
2|Happy|GLAD MERRY JOLLY CHEERY UPBEAT SUNNY BUBBLY CHIPPER ELATED
2|Sad|BLUE DOWN GLUM LOW GLOOMY MOPEY SOMBER
2|Huge|GIANT JUMBO MAMMOTH MASSIVE GIGANTIC IMMENSE TITANIC COLOSSAL VAST
2|Tiny|WEE PUNY MINI PETITE DINKY MINUTE TEENY
2|Fast|QUICK RAPID SWIFT FLEET BRISK SPEEDY HASTY NIMBLE
2|Brave|BOLD GUTSY PLUCKY DARING VALIANT HEROIC FEARLESS
2|Clever|SMART BRIGHT SHARP ASTUTE BRAINY WITTY SHREWD
2|Chat|GAB NATTER YAK BABBLE CHATTER PRATTLE JABBER
2|Run|DASH SPRINT BOLT JOG RACE SCURRY SCAMPER HURRY
2|Walk|STROLL AMBLE HIKE TREK MARCH STRIDE SAUNTER WANDER TRUDGE PLOD
2|Hit|PUNCH SLAP SMACK WHACK BASH THUMP SOCK CLOBBER BOP BELT
2|Throw|TOSS HURL FLING CHUCK LOB PITCH CAST HEAVE SLING
2|Cut|SNIP CHOP SLICE CARVE DICE TRIM HACK SEVER CLIP
2|Laugh|GIGGLE CHUCKLE CHORTLE SNICKER CACKLE GUFFAW TITTER HOOT
2|Look|PEEK PEER GLANCE STARE GAZE GAWK OGLE SQUINT GLIMPSE SCAN
2|Mistake|ERROR SLIP GAFFE BLUNDER FLUB GOOF BLOOPER HOWLER LAPSE
2|Fight|BRAWL SCUFFLE MELEE FRACAS TUSSLE BOUT CLASH SKIRMISH
2|Money|DOUGH BREAD CASH MOOLAH LOOT BUCKS DINERO CABBAGE CLAMS BRASS
2|Friend|PAL BUDDY MATE CHUM ALLY CRONY BRO AMIGO COMRADE
2|Food|GRUB CHOW NOSH EATS FARE VITTLES
2|Swindle|CON SCAM HOAX RUSE STING DUPE FIDDLE HUSTLE
2|Containers|BOX CRATE CARTON CASE TIN JAR CAN BIN TUB
2|Hairstyles|BOB BUN MULLET PERM MOHAWK BRAID AFRO PIGTAIL QUIFF BEEHIVE CREWCUT
2|Knots|BOWLINE HITCH GRANNY REEF NOOSE LOOP SQUARE SHEEPSHANK
2|Cuts of beef|BRISKET SIRLOIN CHUCK FLANK RUMP SHANK RIB TENDERLOIN ROUND
2|Poker terms|FLUSH STRAIGHT BLUFF RAISE FOLD CALL ANTE POT RIVER FLOP TURN CHECK
2|Golf scores|BIRDIE EAGLE BOGEY PAR ALBATROSS CONDOR ACE
2|Golf clubs|IRON WOOD WEDGE PUTTER DRIVER HYBRID
2|Tennis terms|LOVE DEUCE ACE LET VOLLEY SERVE SMASH LOB RALLY FAULT SET MATCH
2|Baseball terms|STRIKE BALL OUT BUNT HOMER INNING PITCH DIAMOND MOUND PLATE DUGOUT BULLPEN
2|Bowling terms|STRIKE SPARE GUTTER PIN FRAME LANE ALLEY SPLIT TURKEY
2|Yoga poses|COBRA LOTUS TREE PLANK BRIDGE CROW WARRIOR CAMEL PIGEON EAGLE
2|Car parts|BUMPER HOOD TRUNK FENDER CLUTCH AXLE MUFFLER RADIATOR HORN BRAKE WHEEL ENGINE GRILLE DASHBOARD
2|Parts of a shoe|SOLE HEEL TONGUE LACE INSOLE TOE EYELET UPPER
2|Parts of a tree|ROOT TRUNK BRANCH BARK LEAF TWIG CROWN SAP LIMB
2|Parts of a flower|PETAL STEM STAMEN PISTIL SEPAL POLLEN ANTHER STIGMA
2|Parts of a book|SPINE COVER PAGE CHAPTER INDEX JACKET PREFACE GLOSSARY APPENDIX FOREWORD
2|Parts of a castle|MOAT TOWER KEEP TURRET DRAWBRIDGE RAMPART DUNGEON GATEHOUSE
2|Parts of a ship|HULL KEEL BOW STERN DECK MAST RUDDER BRIDGE GALLEY HOLD ANCHOR BOOM
2|Parts of the eye|IRIS PUPIL LENS RETINA CORNEA LID LASH
2|Parts of a bird|BEAK WING TALON FEATHER BILL CREST CLAW PLUME
2|Parts of the face|NOSE CHIN CHEEK BROW LIP JAW TEMPLE EYE MOUTH EAR
2|Parts of the hand|PALM THUMB KNUCKLE WRIST NAIL FINGER
2|Bones|FEMUR TIBIA RIB SKULL SPINE PELVIS ULNA RADIUS HUMERUS FIBULA PATELLA STERNUM
2|Organs|HEART LIVER LUNG KIDNEY BRAIN STOMACH SPLEEN BLADDER COLON PANCREAS SKIN GUT
2|Computer parts|MOUSE KEYBOARD MONITOR SCREEN CHIP CURSOR MODEM ROUTER SERVER
2|Computer commands|SAVE COPY PASTE CUT PRINT UNDO DELETE REFRESH SCROLL CLICK DRAG
2|Keyboard keys|SHIFT ENTER ESCAPE SPACE TAB DELETE HOME END CONTROL OPTION RETURN INSERT
2|Baking verbs|KNEAD WHISK FOLD BEAT SIFT CREAM GLAZE PROOF ROLL
2|Cooking methods|BAKE BOIL FRY GRILL ROAST STEAM POACH BRAISE SAUTE SEAR BROIL STEW SMOKE TOAST
2|Sandwiches|CLUB REUBEN SUB HERO HOAGIE PANINI WRAP GYRO MELT
2|Teas|GREEN BLACK OOLONG CHAI MATCHA JASMINE HERBAL MINT CHAMOMILE ROOIBOS DARJEELING
2|Wines|MERLOT SHIRAZ RIESLING MALBEC CHABLIS RIOJA CHIANTI PINOT ROSE PORT SHERRY CHAMPAGNE PROSECCO ZINFANDEL CLARET
2|Beers|LAGER ALE STOUT PORTER PILSNER BITTER BOCK WHEAT SAISON
2|Sauces|PESTO SALSA GRAVY KETCHUP MUSTARD MAYO AIOLI RELISH TAHINI HOISIN SRIRACHA TABASCO RANCH
2|Soups|CHOWDER BISQUE BROTH GAZPACHO MINESTRONE BORSCHT CONSOMME RAMEN PHO GUMBO
2|Mexican food|TACO BURRITO NACHO ENCHILADA QUESADILLA TAMALE FAJITA TOSTADA CHURRO SALSA GUACAMOLE
2|Japanese food|SUSHI SASHIMI TEMPURA RAMEN UDON SOBA MISO TERIYAKI EDAMAME WASABI TOFU GYOZA
2|Ways to cook eggs|POACHED FRIED SCRAMBLED BOILED BAKED DEVILED CODDLED SHIRRED
2|Cocktails|MOJITO MARTINI DAIQUIRI MARGARITA NEGRONI SIDECAR GIMLET COSMO MANHATTAN SCREWDRIVER BELLINI
2|The Beatles|JOHN PAUL GEORGE RINGO
2|Seven dwarfs|DOC GRUMPY HAPPY SLEEPY BASHFUL SNEEZY DOPEY
2|Santa's reindeer|DASHER DANCER PRANCER VIXEN COMET CUPID DONNER BLITZEN RUDOLPH
2|Greek gods|ZEUS HERA ATHENA APOLLO ARES HERMES POSEIDON HADES ARTEMIS HEPHAESTUS DEMETER APHRODITE DIONYSUS EROS NIKE HESTIA
2|Roman gods|JUPITER MARS VENUS MERCURY NEPTUNE PLUTO JUNO MINERVA VULCAN DIANA CUPID BACCHUS CERES JANUS SATURN
2|Norse gods|ODIN THOR LOKI FREYA BALDER TYR HEIMDALL FRIGG
2|Shakespeare plays|HAMLET MACBETH OTHELLO TEMPEST CYMBELINE PERICLES CORIOLANUS|shakespeare
2|Shakespeare characters|ROMEO JULIET HAMLET OTHELLO IAGO PUCK LEAR PORTIA OPHELIA BANQUO PROSPERO FALSTAFF MACBETH|shakespeare
2|Musicals|CATS GREASE HAIR RENT CHICAGO EVITA ANNIE WICKED OLIVER HAMILTON OKLAHOMA COMPANY FOLLIES CABARET
2|Pixar films|CARS UP BRAVE COCO SOUL LUCA ONWARD RATATOUILLE
2|Disney princesses|ARIEL BELLE JASMINE AURORA MULAN MOANA CINDERELLA POCAHONTAS TIANA RAPUNZEL MERIDA
2|Friends characters|ROSS RACHEL MONICA CHANDLER JOEY PHOEBE
2|The Simpsons|HOMER MARGE BART LISA MAGGIE MOE NED APU BURNS KRUSTY OTTO MILHOUSE
2|Muppets|KERMIT PIGGY GONZO FOZZIE ANIMAL BEAKER SCOOTER STATLER WALDORF
2|Sesame Street|ELMO BERT ERNIE GROVER OSCAR ZOE COUNT ABBY
2|Batman villains|JOKER PENGUIN RIDDLER BANE SCARECROW CATWOMAN
2|Superheroes|FLASH HULK THOR STORM ROGUE WOLVERINE AQUAMAN CYCLOPS BEAST DAREDEVIL BATMAN SUPERMAN
2|Star Wars|YODA LUKE LEIA HAN VADER CHEWIE REY FINN POE LANDO JABBA
2|Winnie the Pooh|POOH PIGLET TIGGER EEYORE OWL RABBIT KANGA ROO
2|Peanuts|SNOOPY CHARLIE LUCY LINUS SALLY SCHROEDER WOODSTOCK FRANKLIN MARCIE
2|Scooby-Doo gang|SCOOBY SHAGGY FRED DAPHNE VELMA SCRAPPY
2|Ninja Turtles|LEONARDO DONATELLO RAPHAEL MICHELANGELO|turtles
2|Painters|MONET MANET DEGAS RENOIR PICASSO DALI MATISSE CEZANNE VERMEER TURNER CONSTABLE KLIMT MUNCH GOYA WARHOL POLLOCK ROTHKO RAPHAEL TITIAN
2|Composers|BACH MOZART BEETHOVEN CHOPIN HANDEL HAYDN LISZT VERDI WAGNER BRAHMS ELGAR HOLST RAVEL PUCCINI VIVALDI SCHUBERT
2|Poets|KEATS BYRON SHELLEY FROST BLAKE WORDSWORTH POE DICKINSON WHITMAN TENNYSON ELIOT YEATS DONNE
2|Authors|DICKENS AUSTEN ORWELL TWAIN HEMINGWAY TOLKIEN STEINBECK TOLSTOY WILDE BRONTE WOOLF KAFKA CHRISTIE
2|Scientists|NEWTON EINSTEIN DARWIN CURIE GALILEO TESLA EDISON HAWKING PASTEUR KEPLER BOHR FARADAY
2|Units named after people|NEWTON TESLA CURIE WATT VOLT OHM KELVIN JOULE HERTZ PASCAL FARAD
2|Car makes|FORD HONDA TOYOTA NISSAN AUDI TESLA JAGUAR MINI FIAT VOLVO SAAB KIA MAZDA DODGE JEEP LEXUS BUICK PORSCHE FERRARI LOTUS SUBARU
2|Horses|PONY MARE STALLION FOAL COLT FILLY BRONCO MUSTANG STEED GELDING
2|Dog commands|SIT STAY HEEL FETCH ROLL BEG DOWN COME SPEAK SHAKE
2|Gases|OXYGEN HYDROGEN NITROGEN HELIUM NEON ARGON OZONE METHANE PROPANE BUTANE CHLORINE RADON XENON
2|Things with wings|PLANE BIRD BAT ANGEL FAIRY DRAGON MOTH BUTTERFLY
2|Weapons|SWORD SPEAR PIKE AXE MACE LANCE DAGGER BOW HALBERD FLAIL CLUB SABRE CROSSBOW
2|Sewing kit|NEEDLE THREAD THIMBLE BOBBIN SPOOL PIN BUTTON PATTERN
2|Theater terms|WINGS STAGE CURTAIN PROP CUE ENCORE ACT SCENE
2|Rocks|GRANITE MARBLE SLATE BASALT QUARTZ LIMESTONE SANDSTONE FLINT CHALK SHALE PUMICE OBSIDIAN
2|Winter sports|SKI SLED LUGE CURLING BIATHLON SKELETON BOBSLED SNOWBOARD
2|Martial arts|KARATE JUDO AIKIDO TAEKWONDO SUMO JUJITSU KENDO CAPOEIRA
2|Animal sounds|MOO OINK BAA WOOF MEOW NEIGH QUACK HOOT ROAR HISS BARK CLUCK GROWL PURR CHIRP
2|Animal homes|NEST DEN HIVE BURROW LAIR WARREN STABLE KENNEL STY COOP SETT LODGE HUTCH EYRIE
2|Pizza toppings|PEPPERONI MUSHROOM OLIVE ONION SAUSAGE HAM PINEAPPLE ANCHOVY BACON PEPPER SPINACH
2|Mushrooms|BUTTON PORTOBELLO SHIITAKE CHANTERELLE MOREL OYSTER TRUFFLE ENOKI CREMINI PORCINI
2|Onion family|SHALLOT LEEK CHIVE GARLIC SCALLION ONION
2|Dinosaurs|RAPTOR TRICERATOPS STEGOSAURUS BRONTOSAURUS DIPLODOCUS IGUANODON ALLOSAURUS
2|Pirate gear|PLANK TREASURE CUTLASS EYEPATCH GALLEON DOUBLOON PARROT ANCHOR MUTINY RUM
2|Circus acts|CLOWN ACROBAT JUGGLER TRAPEZE RINGMASTER TIGHTROPE UNICYCLE
2|Poetry forms|SONNET HAIKU LIMERICK ODE ELEGY BALLAD EPIC VILLANELLE

3|Animal groups|PRIDE PACK SCHOOL HERD FLOCK POD MURDER GAGGLE SWARM COLONY TROOP PARLIAMENT
3|Male animals|BULL STAG BOAR RAM COCK DRAKE GANDER BUCK STALLION TOM JACK
3|Female animals|COW DOE EWE HEN SOW MARE VIXEN NANNY JENNY DAM QUEEN
3|Constellations|ORION LYRA DRACO LEO ARIES CYGNUS PEGASUS PHOENIX CASSIOPEIA ANDROMEDA HYDRA CRUX
3|Famous ships|TITANIC BOUNTY BEAGLE MAYFLOWER ENDEAVOUR VICTORY ENTERPRISE ARGO NAUTILUS BISMARCK
3|TV detectives|HOLMES POIROT MARPLE COLUMBO MONK KOJAK MORSE LUTHER
3|Bond films|GOLDFINGER THUNDERBALL MOONRAKER OCTOPUSSY GOLDENEYE SKYFALL SPECTRE
3|Apostles|PETER JAMES JOHN ANDREW THOMAS MATTHEW PHILIP JUDE SIMON JUDAS BARTHOLOMEW
3|Renaissance artists|LEONARDO DONATELLO RAPHAEL MICHELANGELO TITIAN BOTTICELLI GIOTTO|turtles
3|Car models|BEETLE MUSTANG CIVIC COROLLA CAMRY ACCORD FIESTA CORVETTE PRIUS FOCUS GOLF CHARGER BRONCO
3|Programming languages|JAVA PYTHON RUBY SWIFT PERL RUST GO KOTLIN SCALA DART PASCAL BASIC COBOL ELIXIR
3|Tech companies|APPLE AMAZON GOOGLE META ORACLE INTEL CISCO ADOBE NETFLIX UBER TESLA SONY DELL
3|Rivers|NILE AMAZON THAMES SEINE DANUBE RHINE GANGES VOLGA YUKON MISSISSIPPI HUDSON TIGRIS INDUS JORDAN CONGO
3|Mountains|EVEREST DENALI FUJI KILIMANJARO OLYMPUS RAINIER SHASTA ELBRUS MATTERHORN
3|Deserts|SAHARA GOBI MOJAVE KALAHARI ATACAMA SONORAN ARABIAN
3|Islands|CUBA BALI JAVA CRETE MALTA SICILY IBIZA TAHITI FIJI HAWAII JAMAICA ICELAND GUAM CAPRI CORFU
3|Armor|HELMET GAUNTLET SHIELD VISOR BREASTPLATE CHAINMAIL
3|Patterns|PLAID TARTAN PAISLEY STRIPE CHECK HOUNDSTOOTH CHEVRON HERRINGBONE ARGYLE GINGHAM FLORAL
3|Units of volume|CUP PINT QUART GALLON LITER GILL BARREL TEASPOON OUNCE
3|Units of weight|POUND OUNCE TON GRAM STONE KILO CARAT GRAIN
3|Eyewear|GLASSES GOGGLES MONOCLE SPECTACLES CONTACTS SHADES BIFOCALS
3|Slang for police|COPS FUZZ FEDS HEAT PLOD BOBBIES
3|Slang for nose|SNOUT HOOTER CONK SNOZ BEAK SNIFFER
3|Slang for head|NOGGIN NUT DOME BEAN NODDLE NOODLE BONCE MELON
3|Slang for toilet|LOO JOHN CAN HEAD LAV BOG POTTY THRONE PRIVY LATRINE
3|Slang for prison|CAN CLINK SLAMMER POKEY STIR PEN NICK JUG BRIG COOLER HOOSEGOW
3|Hair colors|BLONDE AUBURN BRUNETTE GINGER RED SANDY RAVEN SILVER PLATINUM CHESTNUT
3|Horse colors|BAY ROAN PALOMINO PIEBALD DUN SORREL CHESTNUT GREY PINTO APPALOOSA
3|Beans|KIDNEY PINTO NAVY LIMA BLACK BROAD FAVA MUNG SOY STRING BUTTER GREEN
3|Lettuces|ROMAINE ICEBERG COS ROCKET ARUGULA ENDIVE RADICCHIO FRISEE BUTTER
3|Tomatoes|CHERRY PLUM BEEFSTEAK ROMA HEIRLOOM GRAPE
3|Squashes|ACORN BUTTERNUT SPAGHETTI PUMPKIN ZUCCHINI MARROW GOURD
3|Apple varieties|GALA FUJI BRAEBURN CAMEO JAZZ ENVY HONEYCRISP EMPIRE COX DELICIOUS
3|Sharks|HAMMERHEAD TIGER MAKO BULL NURSE WHALE LEMON THRESHER BASKING
3|Whales|BLUE HUMPBACK SPERM KILLER MINKE RIGHT GREY FIN PILOT BELUGA NARWHAL ORCA
3|Salads|CAESAR COBB GREEK WALDORF CHEF GARDEN NICOISE
3|Ballet terms|PLIE PIROUETTE JETE ARABESQUE TUTU POINTE BARRE ENTRECHAT
3|Tempo markings|ALLEGRO ANDANTE ADAGIO LARGO PRESTO LENTO VIVACE MODERATO
3|Melons|CANTALOUPE HONEYDEW WATERMELON GALIA CASABA
3|Things with shells|EGG TURTLE SNAIL NUT CRAB OYSTER TACO CLAM TORTOISE ARMADILLO
3|Things with scales|FISH SNAKE MAP PIANO DRAGON LIZARD THERMOMETER
3|Things with keys|PIANO LOCK MAP KEYBOARD TYPEWRITER FLORIDA
3|Things with teeth|COMB SAW ZIPPER GEAR SHARK RAKE COG
3|Things with needles|PINE CACTUS COMPASS SYRINGE HEDGEHOG PORCUPINE GAUGE|prickly
3|Things with spines|BOOK CACTUS HEDGEHOG PORCUPINE|prickly
3|Things with rings|SATURN TREE CIRCUS OLYMPICS ONION BOXING PHONE BELL
3|Things that are drawn|BATH SWORD BREATH BLOOD WATER CURTAIN CARD LOTS
3|Things you crack|EGG CODE JOKE SAFE KNUCKLE WHIP NUT SMILE CASE
3|Things you break|RECORD NEWS BREAD HEART PROMISE LAW ICE WIND BANK LEG SILENCE
3|Things you catch|COLD BUS BALL FISH BREATH WAVE FIRE TRAIN
3|Things you shed|SKIN TEARS LIGHT WEIGHT BLOOD HAIR LEAVES
3|Things that run|NOSE RIVER PAINT TAP ENGINE MASCARA CANDIDATE FAUCET
3|Things that bark|DOG TREE SEAL FOX SERGEANT
3|Things that fly|KITE BIRD PLANE TIME RUMOR BAT FLAG SPARKS
3|Things you blow|WIND WHISTLE TRUMPET NOSE FUSE KISS BUBBLE GASKET
3|Things that stick|GLUE TAPE STAMP MAGNET BURR GUM LEECH VELCRO
3|Things you flip|PANCAKE COIN BURGER SWITCH LID
3|Things you roll|DICE DOUGH EYES CARPET SLEEVES CREDITS SUSHI BARREL
3|Things you pitch|TENT BALL IDEA TAR ROOF
3|Names that are verbs|BILL ROB PAT SUE MARK CHUCK NICK DREW WILL JIMMY BOB
3|Sound like letters|BEE SEA TEA PEA JAY EYE QUEUE WHY YOU ARE OWE
3|Sound like numbers|WON TOO FOR ATE FORE
3|Sound like do-re-mi|DOE RAY ME FAR SEW TEA
3|Silent K|KNIFE KNEE KNOT KNIGHT KNOCK KNOB KNIT KNEAD KNACK KNELL

4|FIRE ___|MAN WORK PLACE FLY ARM TRUCK WOOD CRACKER ALARM PROOF SIDE WALL BALL
4|___ FLY|FIRE DRAGON BUTTER HORSE HOUSE FRUIT SAND MAY CRANE STONE BLACK
4|___ BALL|FOOT BASE BASKET SNOW EYE MEAT FIRE HAND GUM CANNON PIN ODD SCREW MOTH NET VOLLEY DODGE
4|___ BOARD|SKATE SURF KEY CARD DART CLIP BILL DASH SKIRT CUP BLACK WHITE CHALK SPRING SNOW
4|___ CAKE|CUP PAN CHEESE SPONGE FRUIT CARROT FISH CRAB SHORT POUND COFFEE
4|___ CORN|POP PEPPER CANDY SWEET BABY UNI
4|___ DOG|HOT BULL WATCH TOP LAP UNDER SHEEP SEA CORN HUSH
4|___ FISH|SWORD CAT STAR JELLY GOLD CRAY SHELL BLOW MONK ANGEL SAIL LION DOG
4|___ HOUSE|LIGHT GREEN DOG TREE WARE FARM BOAT FIRE OPERA POWER WHITE GUEST COFFEE
4|___ MAN|SNOW FIRE POST MILK SPIDER BAT SUPER IRON SALES CAVE GENTLE DOOR BOOGEY
4|___ PAPER|NEWS WALL SAND TOILET TISSUE WAX FLY RICE SCRAP
4|___ STONE|KEY LIME MILE HAIL CORNER BRIM TOMB GALL SAND FLAG COBBLE HEAD
4|___ BERRY|STRAW BLUE BLACK RASP GOOSE CRAN MUL ELDER HUCKLE BOYSEN
4|___ WOOD|HOLLY DRIFT FIRE HARD SOFT PLY BOX SANDAL DOG RED ROSE
4|___ WORM|BOOK SILK EARTH TAPE RING GLOW WOOD INCH
4|___ BUG|BED LADY LOVE JUNE STINK LITTER FIRE
4|___ BELL|BLUE DOOR COW BAR DUMB SLEIGH DIVING HAND
4|___ LINE|COAST SKY DEAD PUNCH HEAD FINISH TIME HOT PIPE HAIR BEE STORY CLOTHES DATE TOW
4|___ POINT|BALL MATCH NEEDLE CHECK VIEW BREAK GUN KNIFE STAND BOILING
4|___ SHIP|FRIEND WAR BATTLE SPACE HARD LEADER MEMBER OWNER
4|___ LIGHT|FLASH SPOT MOON SUN HEAD STAR TORCH CANDLE DAY LIME SKY STOP
4|___ WATER|RAIN SEA SALT FRESH BACK DISH BREAK TOILET HOLY UNDER WHITE
4|___ BAG|HAND SAND BEAN TEA AIR GOODY WIND DOGGY MONEY SCHOOL
4|___ TAIL|PONY PIG COCK DOVE FISH SWALLOW RAT BOB
4|___ BONE|BACK WISH CHEEK JAW FUNNY COLLAR HERRING TROM BREAST THIGH
4|___ NUT|DOUGH CHEST COCO PEA HAZEL BUTTER BRAZIL PINE WING HEALTH
4|___ APPLE|PINE CRAB BIG CANDY TOFFEE CUSTARD
4|___ CHAIR|ARM WHEEL HIGH ROCKING DECK PUSH ELECTRIC EASY BEAN
4|___ PIE|APPLE PUMPKIN PORK COTTAGE SHEPHERD MUD CUTIE POT HUMBLE CHERRY
4|SUN ___|FLOWER BURN DIAL SET RISE SHINE GLASSES DAY SCREEN BATHE BEAM STROKE ROOF
4|MOON ___|LIGHT SHINE BEAM WALK STONE STRUCK SHOT CAKE PIE
4|STAR ___|FISH DUST LIGHT BOARD GAZER STRUCK FRUIT BURST
4|SEA ___|HORSE WEED SHELL LION FOOD SIDE GULL SHORE BED
4|WATER ___|MELON FALL PROOF COLOR MARK SHED BED LILY FRONT PARK CRESS SLIDE
4|BOOK ___|WORM MARK SHELF CASE END KEEPER STORE CLUB MOBILE
4|FOOT ___|BALL PRINT NOTE STEP PATH HOLD LOOSE WEAR BRIDGE STOOL LOCKER
4|HAND ___|BAG SHAKE CUFF STAND WRITING BOOK RAIL BALL MADE SOME OUT SAW
4|HEAD ___|ACHE BAND LIGHT LINE PHONE QUARTER STAND START STRONG ROOM BOARD MASTER
4|BACK ___|PACK BONE FIRE YARD STAGE SPACE LOG FLIP WATER DROP GAMMON HAND
4|EYE ___|BROW LASH LID BALL SORE WITNESS LINER PATCH SIGHT OPENER SHADOW
4|BUTTER ___|FLY CUP MILK NUT SCOTCH FINGERS BEAN KNIFE
4|HONEY ___|MOON COMB BEE DEW SUCKLE POT BUN
4|SNOW ___|MAN BALL FLAKE BOARD DRIFT STORM SHOE PLOW FALL GLOBE DROP
4|RAIN ___|BOW COAT DROP FALL FOREST STORM CHECK DANCE WATER CLOUD
4|HOT ___|DOG POT SPOT SHOT HEAD TUB CAKE ROD SAUCE LINE PEPPER AIR
4|COW ___|BOY BELL HIDE GIRL LICK SLIP HAND POKE PAT
4|DOG ___|HOUSE SLED FIGHT FOOD PADDLE DAYS WOOD TAG BONE
4|CAT ___|FISH NAP WALK CALL NIP BIRD SUIT GUT
4|HORSE ___|SHOE POWER RADISH FLY PLAY HAIR BACK
4|BLACK ___|BIRD BOARD MAIL SMITH JACK OUT BERRY LIST SHEEP HOLE POOL MARKET
4|RED ___|WOOD HEAD NECK CARPET TAPE EYE WINE CROSS
4|BLUE ___|BERRY BIRD PRINT GRASS BELL COLLAR MOON TOOTH JAY FIN CHEESE
4|GREEN ___|HOUSE HORN BACK LAND THUMB FINCH ROOM LIGHT BEAN
4|WHITE ___|HOUSE BOARD WASH WATER NOISE OUT KNIGHT LIE WINE
4|GOLD ___|FISH MINE RUSH SMITH MEDAL DIGGER FINCH LEAF STAR
4|BIG ___|APPLE TOP BEN FOOT DIPPER BANG MOUTH SHOT WIG CHEESE WHEEL DEAL
4|JACK ___|POT KNIFE RABBIT FRUIT HAMMER DAW
4|___ MAIL|BLACK CHAIN SNAIL VOICE JUNK FAN AIR HATE
4|___ CODE|MORSE ZIP AREA DRESS BAR SOURCE CHEAT POSTAL
4|___ CARD|CREDIT POST GREETING BIRTHDAY REPORT WILD SCORE FLASH GIFT BUSINESS RED YELLOW
4|___ TRAP|MOUSE SAND SPEED FLY TOURIST DEATH BEAR RAT
4|___ PARTY|TEA BLOCK HEN STAG SEARCH SURPRISE POOL DINNER COCKTAIL BIRTHDAY THIRD
4|___ JAM|TRAFFIC PAPER TOE LOG PEARL
4|___ ROOM|BATH BED LIVING DINING MUSH BALL STORE LEG ELBOW HEAD SHOW CLASS BACK
4|___ STAR|POP ROCK SHOOTING MOVIE LODE DEATH NORTH SUPER
4|___ FALL|WATER RAIN SNOW NIGHT DOWN FREE PIT LAND FOOT WIND SHORT
4|___ HOLE|BLACK KEY PORT WORM MAN FOX BUTTON LOOP POT PEEP PIN RABBIT
4|___ LOCK|DEAD PAD GRID WED AIR ARM HEAD
4|___ CHIP|MICRO BLUE POTATO CHOCOLATE SILICON POKER
4|___ BREAD|SHORT GINGER CORN SWEET FLAT BANANA GARLIC MONKEY SODA
4|___ BUTTER|PEANUT APPLE COCOA SHEA ALMOND
4|___ SAUCE|SOY HOT FISH APPLE CHEESE TOMATO OYSTER PLUM TARTAR BARBECUE
4|___ TIME|BED OVER HALF PRIME SHOW DAY NIGHT LUNCH TEA SPRING FULL PART
4|___ MARK|BOOK WATER POCK LAND BIRTH QUESTION TRADE HALL BENCH
4|___ PRINT|FOOT FINGER BLUE PAW SMALL FINE THUMB LEOPARD
4|___ SHOT|MOON BIG MUG GUN HOT BUCK SNAP SLING EAR JUMP SCREEN
4|___ CRACKER|NUT FIRE WISE SAFE CHEESE CREAM
4|___ KNIFE|POCKET BUTTER STEAK JACK BOWIE PEN CARVING PUTTY BREAD
4|Palindromes|KAYAK LEVEL RADAR CIVIC ROTOR REFER MADAM NOON SOLOS TENET RACECAR STATS
4|Anagrams of POST|POTS STOP TOPS SPOT OPTS POST
4|Anagrams of STALE|STEAL LEAST SLATE TALES TEALS STALE
4|Anagrams of LISTEN|SILENT ENLIST TINSEL INLETS LISTEN
`;

/** Body parts a word can open with, for the rule category below. */
const BODY_STARTS = ['ARM', 'HAND', 'LEG', 'SHIN', 'EAR', 'HIP', 'KNEE', 'LIP', 'CHIN', 'TOE', 'NOSE', 'HEEL', 'BACK', 'FOOT', 'HEAD', 'NECK', 'CHEST', 'EYE', 'JAW', 'LUNG', 'LIVER', 'SKIN'];

/** Numbers hidden inside a longer word. */
const HIDDEN_NUMBERS = ['ONE', 'TWO', 'SIX', 'TEN', 'NINE', 'EIGHT'];

const RULES: RuleCategory[] = [
  {
    tier: 4,
    name: 'Starts with a body part',
    // The word has to carry on past the body part — `ARM` itself is not
    // "starting with" anything — and a plural (`EARS`, `EYES`) is the body part
    // rather than a word that happens to open with one.
    test: (word) =>
      BODY_STARTS.some(
        (part) => word.startsWith(part) && word.length > part.length && word !== `${part}S`,
      ),
    seed: 'ARMADA HANDLE LEGEND SHINDIG EARNEST HIPSTER KNEEL LIPSTICK CHINCHILLA TOENAIL HANDSOME ARMOR',
  },
  {
    tier: 4,
    name: 'Hidden numbers',
    test: (word) => HIDDEN_NUMBERS.some((n) => word !== n && word.includes(n)),
    seed: 'OFTEN CANINE LONELY WEIGHT FREIGHT PHONE MONEY HONEY KITTEN TENDON ATTENTION',
  },
];

/* ------------------------------------------------------------------ */
/* Assembly                                                            */
/* ------------------------------------------------------------------ */

function build(): Category[] {
  const out: Category[] = [];

  for (const line of LISTS.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    const [tier, name, words, family] = trimmed.split('|');
    out.push({
      id: out.length,
      name: name as string,
      tier: Number(tier) as Category['tier'],
      words: dedupe((words as string).split(/\s+/)),
      family: family ?? null,
    });
  }

  // Rule categories are resolved against the whole vocabulary, so they go last
  // and see every list above.
  const vocabulary = new Set(out.flatMap((category) => category.words));
  for (const rule of RULES) {
    const seed = rule.seed.split(/\s+/);
    for (const word of seed) vocabulary.add(word);
    const words = [...vocabulary].filter(rule.test).sort();
    out.push({ id: out.length, name: rule.name, tier: rule.tier, words, family: null });
  }

  return out;
}

function dedupe(words: string[]): string[] {
  return [...new Set(words)];
}

export const CATEGORIES: readonly Category[] = build();

/** Every category each word belongs to. The one index the solver needs. */
export const MEMBERSHIP: ReadonlyMap<string, readonly number[]> = (() => {
  const map = new Map<string, number[]>();
  for (const category of CATEGORIES) {
    for (const word of category.words) {
      const list = map.get(word);
      if (list) list.push(category.id);
      else map.set(word, [category.id]);
    }
  }
  return map;
})();
